[package]
authors = ["ryym <ryym.64@gmail.com>"]
name = "sample"
version = "0.1.0"

[dependencies]
actix-web = "0.7.5"
dotenv = "0.13.0"
env_logger = "0.5.13"

[dependencies.diesel]
features = ["postgres"]
version = "1.3.2"
