version: 2
jobs:
  build:
    docker:
      # - image: rust:1.28-slim-stretch
      - image: docker:18.06
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run: docker --version
      - run: docker build .

      # - run: cargo --version
      # - checkout
      # - run: cargo build
