version: 2
jobs:
  test:
    docker:
      - image: rust:1.28-stretch
        environment:
          CARGO_HOME: /cargo
    steps:
      - checkout
      - run: cargo --version

      - restore_cache:
          key: cargo-{{checksum "Cargo.lock"}}
      - restore_cache:
          key: target-debug-{{checksum "Cargo.lock"}}

      - run: cargo test

      - save_cache:
          key: cargo-{{checksum "Cargo.lock"}}
          paths:
            - "/cargo"
      - save_cache:
          key: target-debug-{{checksum "Cargo.lock"}}
          paths:
            - "./target"

  build:
    docker:
      - image: rust:1.28-stretch
        environment:
          CARGO_HOME: /cargo
    steps:
      - checkout

      - run: cargo --version

      - restore_cache:
          key: cargo-{{checksum "Cargo.lock"}}
      - restore_cache:
          key: target-release-{{checksum "Cargo.lock"}}

      - run: cargo build --release

      - run: mkdir dist

      - save_cache:
          key: cargo-{{checksum "Cargo.lock"}}
          paths:
            - "/cargo"
      - save_cache:
          key: target-release-{{checksum "Cargo.lock"}}
          paths:
            - "./target"

      - persist_to_workspace:
          root: target
          paths:
            - release/sample

  release:
    docker:
      - image: ryym/heroku-docker
    steps:
      - checkout

      - attach_workspace:
          at: target
      - run: du -h target/release

      - setup_remote_docker:
          version: 18.06.0-ce
      - run: docker --version
      - run: docker info

      - run: mv target/release/sample .

      # HEROKU_API_KEY must be set.
      - run: heroku --version
      - run: heroku container:login
      - run: heroku container:push -a rust-sample --recursive

      # Though the doc says there is no need to specify a release image,
      # Heroku does not run the release phase task without this.
      # https://devcenter.heroku.com/articles/container-registry-and-runtime#release-phase
      - run: heroku container:release release web -a rust-sample

workflows:
  version: 2

  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - release

  build-release:
    jobs:
      - build:
          filters:
            branches:
              only:
                - release
      - release:
          requires:
            - build
          filters:
            branches:
              only:
                - release
