version: 2
jobs:
  build:
    docker:
      - image: rust:1.28-slim-stretch
    steps:
      - checkout

      - run: cargo --version
      - run: cargo build --release
      - run: mkdir dist

      - persist_to_workspace:
          root: target
          paths:
            - release/tmp-rs

  pack:
    docker:
      - image: docker:18.06
    steps:
      - checkout

      - attach_workspace:
          at: target
      - run: du -h target/release

      - setup_remote_docker:
          version: 18.06.0-ce

      - run: mv target/release/tmp-rs .
      - run: docker --version
      - run: docker build -t tmp-rs .
      - run: docker run --rm -t tmp-rs

workflows:
  version: 2
  build-pack:
    jobs:
      - build
      - pack:
          requires:
            - build
